### ISSUE TITLE
walletapi's listpayment/listinvoices/getchannels crashes the node if no LN is connected.

### ISSUE THREAD

**Issue by markcryptohash** [imperviousai/imp-daemon#37]
Firing these API calls, causes segfault if there is no LN node connected. This is due to the call to a 'nil' Node struct. So.... the fix is probably in server/lighting/lighting.go to do a quick check to see if there is a node connected, if so continue, else simple return "no node connected"...and also not segfault.

**Comment by markhandlersec** [comment]
Fixed in https://github.com/imperviousai/imp-daemon/pull/39
